backend add a database
flipkoehler/capstone-project-ts pull request #16
Opened 2022-12-19 14:26 UTC by flipkoehler

2022-12-20 10:14 UTC, ThomasKirst requested changes
Good work overall!
You started with TypeScript, you might want to add a few sprinkles of type annotations here and there.
This would also include renaming all .js files to .ts. Maybe it´s some refactoring idea for the holidays? ;)

2022-12-20 10:14 UTC, ThomasKirst commented on db/models/Movie.js
> +  // belongs_to_collection: { type: String, required: false },
Unused code!

2022-12-20 10:14 UTC, ThomasKirst commented on components/RandomMoviePicker/RandomMoviePicker.js
> +  }
Can this possibly be not set?

2022-12-20 10:14 UTC, ThomasKirst commented on components/Quiz/quizLogic.js
>      const randomNumber = Math.floor(Math.random() * filteredMovies.length);
I think I saw something similar already (a few lines down).
This could be perfectly handled by a function, which you can import wherever it´s needed.

2022-12-20 11:55 UTC, flipkoehler commented on components/RandomMoviePicker/RandomMoviePicker.js
> +  }
I have tried it without this code, but I always received the following error: 
"TypeError: Cannot read properties of undefined (reading 'poster_path')" (and all the other properties when I comment out the poster_path) 
It seems like the this function has a small delay in receiving the data. When the return starts, the "pickedMovie" is not set I guess . The "if function" is fixing that. I hope its okay leaving the snippet in my code.

2022-12-20 11:57 UTC, flipkoehler commented on lib/fetch.js
> +  useEffect(() => {
My goal for the upcoming holidays is to replace some components with typescript. For now I am working on the TS tutorial 👍

2022-12-20 16:26 UTC, flipkoehler commented on components/Quiz/quizLogic.js
>      const randomNumber = Math.floor(Math.random() * filteredMovies.length);
i fixed it!

2022-12-21 07:34 UTC, flipkoehler commented
> Philip, I looked at your code at a glance. Looks good to me so far.
> 
> But I wonder that you refer direct to /api and not to the collection e.g. /api/movies.
> 
> I found out that when you open the Vercel preview the first time no data is shown. When you open the preview the second time data is shown directly. Same happens with Alex's App.
> 
> Maybe a try and catch block will help?
> 
> Nevertheless very nice! :)

Hey Marvin,

thanks for the review :)

A good idea with the try & catch Block. I will try that in another ticket.

2022-12-21 08:21 UTC, ThomasKirst requested changes
I left only one more comment, after that change I would call it a wrap :)

2022-12-21 08:21 UTC, ThomasKirst commented on components/RandomMoviePicker/RandomMoviePicker.js
>  }
Much better!
Only one more remark: this is just a plain function, not a component.
Thus, I would give it an "active" name like `pickRandomMovie(...)` – camelCase.
Lastly, the function would be better placed in your `lib` folder, since it´s not a component.

2022-12-21 08:43 UTC, flipkoehler commented on components/RandomMoviePicker/RandomMoviePicker.js
>  }
thank you for the review :) 
i have fixed that

2022-12-21 09:01 UTC, merged