Add a second question, rebuild the quiz.js and add an array for the questions
flipkoehler/capstone-project-ts pull request #9
Opened 2022-12-16 13:27 UTC by flipkoehler

2022-12-16 14:28 UTC, MerleMak reviewed
Hi Philip,
This looks good! Again, appreciate the comments in your code 🙏🏻
I left some small remarks and a big one: you should wrap your input field and button in a form :)
Great work so far!

2022-12-16 14:28 UTC, MerleMak commented on components/Quiz/quizLogic.js
> +// okay - I may be stupid. But I really hate the native radio buttons. So here is my styling...
no you are not stupid, smart workaround :D

2022-12-16 14:28 UTC, MerleMak commented on components/Quiz/quizLogic.js
> +const StyledDiv = styled.div`
Can you find a more descriptive name here? Maybe like "AnswerWrapper" or something that doesn't include the word div :D

2022-12-16 14:28 UTC, MerleMak commented on components/Quiz/quizLogic.js
> +          } else return givenAnswers;
why are you returning givenAnswers here?

2022-12-16 14:28 UTC, MerleMak commented on components/Quiz/quizLogic.js
> +        </div>
To be semantically correct this should wrapped in a form :)

2022-12-16 14:28 UTC, MerleMak commented on components/Quiz/quizLogic.js
> +              onChange={() => handleAnswerOption(answer.value)}
The onChange event doesn't make sense here as the user can't type anything, therefore you don't need to keep track if the input value changes. It is only relevant to you as soon as the user decided and clicks "Weiter" :) so on the submit event of a form, that you should add :)

2022-12-16 15:06 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +          } else return givenAnswers;
if the user is clicking "ist mir egal" the array is just passing through :)

2022-12-16 15:09 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +        </div>
wuuupsi 😵‍💫

2022-12-16 15:14 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +              onChange={() => handleAnswerOption(answer.value)}
gut recommendation! Thanks :) 
it was "doppelgemoppelt"

2022-12-16 15:26 UTC, stefankorder requested changes
Good work! Just one comment.

2022-12-16 15:26 UTC, stefankorder commented on components/Quiz/quizLogic.js
> +        });
I would suggest you to use only one filtering method instead of two. It is not recommended to concatenate filter method to filter method. Try to find search criteria for both use cases.

2022-12-16 15:28 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +    <form>
cheeeeck :)

2022-12-16 16:06 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +        });
this is a though one. I have no clue 😵‍💫 
But I will try my best tomorrow

2022-12-16 18:42 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +        });
okay. Walking around the neighborhood was a good idea :) 
I solved this and reduced this filter method to one

2022-12-17 10:14 UTC, ufelgen reviewed
Philip, ich bin hart begeistert!!!! das ist so cool!!!!

ich hab ein paar erbsenzählerhafte Kommentare gemacht... und ich hab mir deine Preview angesehen und würde mir noch einen Button wünschen, der mich von der "random movie" page wieder zurück zur Hauptseite führt :) und bei deinem Quiz ploppt nach der 2. Frage ganz kurz Frage 3 auf, die ja nicht existiert...

aber wie gesagt: MEGA!!!!!

2022-12-17 10:14 UTC, ufelgen commented on components/Quiz/quizLogic.js
> +  // uesd for routing
```suggestion
  // used for routing
```

2022-12-17 10:14 UTC, ufelgen commented on components/Quiz/quizLogic.js
> +  // Function takes the input value and add store it to the array with the current answers
```suggestion
  // Function takes the input value and stores it in the array with the current answers
```

2022-12-17 10:14 UTC, ufelgen commented on components/Quiz/quizLogic.js
> +  // Function handels the Click on the Button. It sets the current step the user is in
```suggestion
  // Function handles the Click on the Button. It sets the current step the user is in
```

2022-12-17 10:14 UTC, ufelgen commented on components/Quiz/quizLogic.js
> +    setGivenAnswers([...givenAnswers]);
das versteh ich leider nicht... vielleicht kannst du mir das am Montag mal erklären, bin neugierig :) brauchst du beide Zeilen?

2022-12-17 10:14 UTC, ufelgen commented on pages/errorpages/no-movie.js
> +        Klicke hier für eine zufällige Filmempfehlung
geil!!

2022-12-17 10:30 UTC, flipkoehler commented on assets/data/movieData.js
>      spoken_languages: [
exakt! Habe die Daten aus der Schnittstelle :) 
Das Release date werde ich ummappen beim GET.

2022-12-17 10:31 UTC, flipkoehler commented on assets/data/questionData.js
> +            max: 9999,
wer weiß was die Zukunft so bringt 😄 
Guinness World Records says [the longest film ever made is "The Cure for Insomnia"](https://www.guinnessworldrecords.com/world-records/69763-longest-film-made) released in 1987[. ](https://www.guinnessworldrecords.com/world-records/69763-longest-film-made)The 85-hour experimental film was directed by John Henry Timmis IV.

2022-12-17 10:32 UTC, flipkoehler commented on assets/data/questionData.js
> +    question: "Frage 1/2: Wie lange darf dein Film heute dauern?",
yes! Es kommt auch noch ein schönerer Indikator. Aber fürs erste reicht mir das :)

2022-12-17 10:33 UTC, flipkoehler commented on assets/data/questionData.js
> +            max: 1987,
guter Punkt! Ich bin tatsächlich auch noch nicht ganz zufrieden mit der Auswahl. Habe ein kleine handschriftliche Liste - da kommt der Vorschlag mit drauf.

2022-12-17 10:33 UTC, flipkoehler commented on assets/data/questionData.js
> +        answer: "Moderne Klassiker",
😄

2022-12-17 10:34 UTC, flipkoehler commented on assets/data/questionData.js
> +];
das wird in den nächsten beiden User Stories befüllt 👍

2022-12-17 10:34 UTC, flipkoehler commented on components/MovieDetailPage/MovieDetailPage.js
> -
das werde ich definitiv nochmal beim "Get" der Daten benötigen. Das kommt dann aber an eine andere Stelle :)

2022-12-17 10:36 UTC, flipkoehler commented on components/Quiz/quizLogic.js
> +    setGivenAnswers([...givenAnswers]);
können wir gerne mal zusammen rüber schauen am Montag :)

2022-12-17 10:37 UTC, flipkoehler commented
> 

Danke Ulli für die Tipps und dein Feedback. Richtig cool, dass du dir die Zeit genommen hast mit Ruhe durchzuschauen 😊

2022-12-17 14:24 UTC, merged